export default {
  GET_TWEETS: 'GET_TWEETS',

  GET_TWEETS_REQUEST: 'GET_TWEETS_REQUEST',
  GET_TWEETS_SUCCESS: 'GET_TWEETS_SUCCESS',
  GET_TWEETS_FAIL: 'GET_TWEETS_FAIL',

  SEARCH_TWEETS: 'SEARCH_TWEETS',
  SEARCH_TWEETS_REQUEST: 'SEARCH_TWEETS_REQUEST',
  SEARCH_TWEETS_SUCCESS: 'SEARCH_TWEETS_SUCCESS',
  SEARCH_TWEETS_FAIL: 'SEARCH_TWEETS_FAIL',
}